customhost = "database-1.cqobzg2r7v7a.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "wongyannyiee_employee"
custombucket = "wongyannyiee-employee"
customregion = "us-east-1"
